# Site settings
title: Libin N George
emaila: libinngeorge@gmail.com
email: libinngeorge@arizona.edu
url: https://libin-n-g.github.io/MyProfile/
description: "I am currently pursuing a Master in Information Science with a focus on Machine Learning, after completing my Bachelor’s in Computer Science and Engineering with honors from IIT Palakkad. "
baseurl: /MyProfile
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: libinngeorge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/libinngeorge
  - title: facebook
    url: https://www.facebook.com/libinn.george
  - title: stack-overflow
    url: https://stackoverflow.com/users/7552865/libin-n-george
  - title: bitbucket
    url: http://bitbucket.org/libinngeorge
  - title: github
    url: https://github.com/libin-n-g
  - title: linkedin
    url: https://www.linkedin.com/in/libin-n-george-126b3195
    
download: https://libin-n-g.github.io/MyProfile/Libin_N_George.pdf
# Build settings
markdown: kramdown
permalink: pretty
