# Site settings
title: Libin N George
emaila: libinngeorge@gmail.com
email: 111501015@smail.iitpkd.ac.in
url: https://libin-n-g.github.io/MyProfile
description: "I am undergraduate student of Indian Institute of India, Palakkad persuing B.Tech Computer science and Engineering "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: libinngeorge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/libinngeorge
  - title: facebook
    url: https://www.facebook.com/libinn.george
  - title: stack-overflow
    url: https://stackoverflow.com/users/7552865/libin-n-george
  - title: bitbucket
    url: http://bitbucket.org/libinngeorge
  - title: github
    url: https://github.com/libin-n-g

# Build settings
markdown: kramdown
permalink: pretty
